spring.datasource.url=jdbc:postgresql://dpg-d75376u3jp1c739cdteg-a.oregon-postgres.render.com:5432/lms_db_p53n
spring.datasource.username=lms_db_p53n_user
spring.datasource.password=YHQ3CYBWoiu8LRHXUipoYw5OfapfmPFN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=mySuperSecretKeyForLMSProject123456
app.jwt.expiration=86400000

server.port=${PORT:8080}