spring.datasource.url=jdbc:postgresql://dpg-d70g0q15pdvs7396lkt0-a.oregon-postgres.render.com:5432/management_clui
spring.datasource.username=madhuri
spring.datasource.password=7WCLDHHcfayzr5p4ZLQeJGn5kLTgqC3q

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=mySuperSecretKeyForLMSProject123456
app.jwt.expiration=86400000